//
//  AddFriendsProtocols.swift
//  GrocList
//
//  Created Jatesh Kumar on 01/04/2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Hasnain Kanji
//

import Foundation

// MARK: Wireframe -
protocol AddFriendsWireframeProtocol: class {
    static func createModule () -> AddFriendsViewController
}
// MARK: Presenter -
protocol AddFriendsPresenterProtocol: class {

    var interactor: AddFriendsInteractorInputProtocol? { get set }

    func getAllUsersExceptFriends(roomID: String)
}

// MARK: Interactor -
protocol AddFriendsInteractorOutputProtocol: class {
    func fetchedUsers(users: [User])
    /* Interactor -> Presenter */
}

protocol AddFriendsInteractorInputProtocol: class {

    var presenter: AddFriendsInteractorOutputProtocol? { get set }
    func getAllUsersFromDB(roomID: String)
    /* Presenter -> Interactor */
}

// MARK: View -
protocol AddFriendsViewProtocol: class {

    var presenter: AddFriendsPresenterProtocol? { get set }

    /* Presenter -> ViewController */
    func showLoader()
    func hideLoader()

    func setupUsers(users: [User])
}
