//
//  AddFriendsRouter.swift
//  GrocList
//
//  Created Jatesh Kumar on 01/04/2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Hasnain Kanji
//

import UIKit

final class AddFriendsRouter {

    weak var viewController: UIViewController?

    deinit {
        print("deinit AddFriendsRouter")
    }

    static func createModule() -> AddFriendsViewController {

        // Change to get view from storyboard if not using progammatic UI
        
        let view = contactsStoryboard.instantiateViewController(withIdentifier: "AddFriendsViewController") as? AddFriendsViewController
        let interactor = AddFriendsInteractor()
        let router = AddFriendsRouter()
        let presenter = AddFriendsPresenter(interface: view!, interactor: interactor, router: router)

        view?.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view!
    }
    
    static var contactsStoryboard: UIStoryboard { return UIStoryboard(name: "AddFriends", bundle: Bundle.main)}
}

extension AddFriendsRouter: AddFriendsWireframeProtocol {

}
