disabled_rules: # rule identifiers to exclude from running
    - trailing_whitespace
#    - function_parameter_count
#    - identifier_name
#    - implicit_getter

opt_in_rules:
#    - empty_count
#    - empty_string

excluded: # paths to ignore during linting. overridden by `included`.
    - Carthage
    - Pods
    - fastlane
#    - Motory - Dealer App/Helpers/R-Swift/R.generated.swift
    

# parameterized rules can be customized from this configuration file
file_length:
    - 700
    - 1000

line_length:
    warning: 180
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true

cyclomatic_complexity:
    warning: 22
    error: 27

# parameterized rules are first parameterized as a warning level, then error level.
function_body_length:
    - 150 # warning
    - 200 # error

type_body_length:
    - 300 # warning
    - 400 # error

reporter: "xcode"
