//
//  FriendRequestsRouter.swift
//  GrocList
//
//  Created Jatesh Kumar on 01/04/2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Hasnain Kanji
//

import UIKit

final class FriendRequestsRouter {

    weak var viewController: UIViewController?

    deinit {
        print("deinit FriendRequestsRouter")
    }

    static func createModule() -> UIViewController {

        // Change to get view from storyboard if not using progammatic UI
        let view = requestStoryboard.instantiateViewController(identifier: "FriendRequestsViewController") as? FriendRequestsViewController
        let interactor = FriendRequestsInteractor()
        let router = FriendRequestsRouter()
        let presenter = FriendRequestsPresenter(interface: view!, interactor: interactor, router: router)

        view?.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view!
    }
    
    static var requestStoryboard: UIStoryboard {return UIStoryboard(name: "AddFriends", bundle: nil)}
    
}

extension FriendRequestsRouter: FriendRequestsWireframeProtocol {

}
