//
//  ChatProtocols.swift
//  GrocList
//
//  Created Jatesh Kumar on 06/04/2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Hasnain Kanji
//

import Foundation
import UIKit
// MARK: Wireframe -
protocol ChatWireframeProtocol: class {
    static func createModule (chatKey: String, user: User?) -> UIViewController
}
// MARK: Presenter -
protocol ChatPresenterProtocol: class {

    var interactor: ChatInteractorInputProtocol? { get set }
    func getMessages(chatRoomID: String)
    func sendMessage(chatKey: String, message: [String: String])
}

// MARK: Interactor -
protocol ChatInteractorOutputProtocol: class {
    func fetchedMessages(messages: [Messages])
    /* Interactor -> Presenter */
}

protocol ChatInteractorInputProtocol: class {

    var presenter: ChatInteractorOutputProtocol? { get set }
    func fetchMessagesFromDB(chatRoomID: String)
    func sendMessageIntoDB(chatKey: String, message: [String: String])
    /* Presenter -> Interactor */
}

// MARK: View -
protocol ChatViewProtocol: class {

    var presenter: ChatPresenterProtocol? { get set }

    /* Presenter -> ViewController */
    func showLoader()
    func hideLoader()
    
    func displayChat(chat: [Messages])
}
