//
//  ChatRouter.swift
//  GrocList
//
//  Created Jatesh Kumar on 06/04/2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Hasnain Kanji
//

import UIKit

final class ChatRouter {

    weak var viewController: UIViewController?

    deinit {
        print("deinit ChatRouter")
    }

    static func createModule(chatKey: String) -> UIViewController {

        // Change to get view from storyboard if not using progammatic UI
        let view = chatViewStoryboard.instantiateViewController(identifier: "ChatViewController") as? ChatViewController
        
        let interactor = ChatInteractor()
        let router = ChatRouter()
        let presenter = ChatPresenter(interface: view!, interactor: interactor, router: router)

        view!.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        view?.chatroomKey = chatKey
        return view!
    }
    
    static var chatViewStoryboard: UIStoryboard { return UIStoryboard(name: "Chat", bundle: Bundle.main) }
    
}

extension ChatRouter: ChatWireframeProtocol {

}
