//
//  FriendListProtocols.swift
//  GrocList
//
//  Created Jatesh Kumar on 05/04/2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Hasnain Kanji
//

import Foundation

// MARK: Wireframe -
protocol FriendListWireframeProtocol: class {

}
// MARK: Presenter -
protocol FriendListPresenterProtocol: class {

    var interactor: FriendListInteractorInputProtocol? { get set }
    func getMyFriendList(myUserID: String)
}

// MARK: Interactor -
protocol FriendListInteractorOutputProtocol: class {
    func setFriendListToView(users: [User])
    /* Interactor -> Presenter */
}

protocol FriendListInteractorInputProtocol: class {

    var presenter: FriendListInteractorOutputProtocol? { get set }
    func getUsers(roomID: String)
    /* Presenter -> Interactor */
}

// MARK: View -
protocol FriendListViewProtocol: class {

    var presenter: FriendListPresenterProtocol? { get set }

    /* Presenter -> ViewController */
    func showLoader()
    func hideLoader()
    func updateView(friends: [User])
}
